name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        linter:
          - lint
          - mypy

    steps:
      - uses: actions/checkout@v2
      - name: tox ${{ matrix.linter }}
        uses: docker://snakepacker/python:all
        env:
          TOXENV: ${{ matrix.linter }}
        with:
          args: tox

  build:
    needs: lint
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        toxenv:
          - py37
          - py38
          - py39
          - py310

    steps:
      - uses: actions/checkout@v2

      - name: tox ${{ matrix.toxenv }}
        uses: docker://snakepacker/python:all
        env:
          TOXENV: ${{ matrix.toxenv }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        with:
          args: tox
