name: tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        linter:
          - ruff
          - mypy

    steps:
      - uses: actions/checkout@v2
      - name: Setup python3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Cache virtualenv
        id: venv-cache
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ github.job }}-${{ github.ref }}
      - run: python -m pip install poetry
      - run: poetry install
      - run: poetry run ${{ matrix.linter }} wsrpc_aiohttp
        env:
          FORCE_COLOR: 1

  tests:
    needs: lint
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        python:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"

    steps:
      - uses: actions/checkout@v2
      - name: Setup python${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python }}"
      - name: Cache virtualenv
        id: venv-cache
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ github.job }}-${{ github.ref }}-${{ matrix.python }}
      - run: python -m pip install poetry
      - run: poetry install --with=uvloop
      - name: pytest
        run: >-
          poetry run pytest \
            -vv \
            --cov=wsrpc_aiohttp \
            --cov-report=term-missing \
            --doctest-modules \
            tests
        env:
          FORCE_COLOR: 1

      - run: poetry run coveralls
        env:
          COVERALLS_PARALLEL: "true"
          COVERALLS_SERVICE_NAME: github
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
